### PR TITLE
[Audit Suggestion 2] Check eth1 events type assertion

### PR DESCRIPTION
**Pull request by nkryuchkov**
Avoid panic if event type mismatches

### CODE REVIEW

**Review by y0sher — CHANGES_REQUESTED** [review]
We could probably reduce some code here if we use the switch type of go this way - 
```golang
switch e.Data.(type) {
 case abiParser.OperatorRemovedEvent:
    // here we know for sure e.Data is OperatorRemovedEvent
 default:
     // return malformed event error unknown event
}
```
@olegshmuelov , @moshe-blox  if you have any objections please state them.

**Comment by nkryuchkov** [comment]
@y0sher But then we wouldn't check if `e.Name` contains the same event. Although we could probably remove it

**Comment by y0sher** [comment]
> @y0sher But then we wouldn't check if `e.Name` contains the same event. Although we could probably remove it

Ok than let's keep it like this for now, maybe change to what I suggested as part of a bigger change.

**Review by y0sher — APPROVED** [review]

**Review by moshe-blox — APPROVED** [review]

**Comment by moshe-blox** [comment]
> @y0sher But then we wouldn't check if e.Name contains the same event. Although we could probably remove it

I noticed that event types are already determined by the names, so this check is already being done before fireEvent is called, therefore we don't need to check the event names in Eth1EventHandler (because it's already checked before fireEvent is called in [handleEvent](https://github.com/bloxapp/ssv/blob/ed7b79a6780126cc1999ef25da8ee0057328108b/eth1/goeth/goETH.go#L345)).

Can you confirm @nkryuchkov?

I've made a commit to only check the types, does it make sense for you?

**Comment by nkryuchkov** [comment]
@moshe-blox I think then we need to remove the `Name` field because it's used only in `HandleEventResult` for logging

**Pull request merged**
