### PR TITLE
ssv - Lint - goimports - sorting imports

### PR DESCRIPTION
**Pull request by vinipx**
Sorting imports according to **goimports**

@roman-blox @alonmuroch @lior-blox  please, review

### CODE REVIEW

**Review by roman-blox — COMMENTED** [review]
We need to ignore *.pb.go files

**Comment by vinipx** [comment]
> We need to ignore *.pb.go files

should we adjust **lint.sh** to ignore them? or manually ignore during review?

**Comment by roman-blox** [comment]
@vinipx we have to adjust lint.sh

**Comment by vinipx** [comment]
> @vinipx we have to adjust lint.sh

I will close this PR and open new one with the appropriate changes.

**Comment by roman-blox** [comment]
@vinipx actually you don't need to close a PR, you just need to push changes and the PR will be updated automatically :)

**Comment by vinipx** [comment]
@roman-blox better to have things clean ^^  I cud amend commit, but let's do it properly

**Pull request closed without merging**
