### PR TITLE
Gm/generate operator keys encrypted

### PR DESCRIPTION
**Pull request by guym-blox**

### CODE REVIEW

**Review by y0sher — CHANGES_REQUESTED** [review]
Please add a test that receives an unencrypted key, encrypts it and decrypt and check that it's correct.

**Review by y0sher — DISMISSED** [review]
Lets merge @moshe-blox

**Comment by lior-blox** [comment]
Please add the command to the docs

**Review by lior-blox — CHANGES_REQUESTED** [review]
Add to readme on how to use this command to convert existing

**Review by y0sher — APPROVED** [review]

**Review by moshe-blox — APPROVED** [review]

**Review by y0sher — APPROVED** [review]

**Review by moshe-blox — APPROVED** [review]

**Comment by moshe-blox** [comment]
@andrew-blox can you please confirm that you can generate encrypted keys using the documentation only? (without assistance from anyone)

**Pull request merged**
