### PR TITLE
Fix: typos

### PR DESCRIPTION
**Pull request by omahs**
Fix: typos

### CODE REVIEW

**Comment by moshe-blox** [comment]
> Fix: typos

Hi, thanks a lot!

Can you please change the base branch to stage?

**Comment by omahs** [comment]
@moshe-blox hey, sure! just changed it

**Comment by nivBlox** [comment]
> Fix: typos

Hey @omahs, can you checkout from stage in order to resolve the many changes (501 files)

**Comment by omahs** [comment]
Hey, I just made a new PR from the right branch: https://github.com/bloxapp/ssv/pull/838

**Pull request closed without merging**
