### PR TITLE
feat: rate limit inbound connections by IP

### PR DESCRIPTION
**Pull request by moshe-blox**
Following [Prysm's example](https://github.com/prysmaticlabs/prysm/pull/6780), this PR adds rate limiting in `ConnectionGater` to prevent Syn Flood attacks.

TODO: add unit test

### CODE REVIEW

**Comment by y0sher** [comment]
the issue is that conngater is never used so this has no effect.

**Comment by y0sher** [comment]
> the issue is that conngater is never used so this has no effect.

btw conn gater is passed to libp2p options and used in this PR - #1225 
maybe it worth to merge this into there.

**Comment by moshe-blox** [comment]
> > the issue is that conngater is never used so this has no effect.
> 
> btw conn gater is passed to libp2p options and used in this PR - #1221 maybe it worth to merge this into there.

agreed, although maybe we can merge that one and then this one separately?

**Review by y0sher — APPROVED** [review]

**Comment by moshe-blox** [comment]
On pause, @MatheusFranco99 is checking potential issue where we blindly reject messages (without validating again after rate limit exceeded) and end up losing potential valid messages.

**Review by GalRogozinski — APPROVED** [review]
Test looks ok

Verified by initiating log

**Review by y0sher — APPROVED** [review]

**Pull request merged**
